apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: jx-payments:latest
        imagePullPolicy: Never
        command: ['sh', '-c', 'python manage.py migrate']
      restartPolicy: Never
  backoffLimit: 4