apiVersion: apps/v1
kind: Deployment
metadata:
  name: jx-payments-deployment
  labels:
    app: jx-payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jx-payments
  template:
    metadata:
      labels:
        app: jx-payments
    spec:
      initContainers:
      - name: migrate
        image: jx-payments:latest
        imagePullPolicy: Never
        command: ['sh', '-c', 'echo The app is running! && sleep 10']
      containers:
      - name: jx-payments
        image: jx-payments:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080